### PR TITLE
[#167580154] Add recommendation for more mirrors

### PR DESCRIPTION
**Pull request by DennyHoang**
Signed-off-by: Raymond Lee <rlee@pivotal.io>

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @DennyHoang 
This looks like good info to add. I'll take a look, give it an edit, and get back to you if I have questions.

**Comment by jncd** [comment]
First questions: 

1. Does 
"instances where ClamAV is installed."  =  "VMs in my PCF foundation"?

If I have installed ClamAV, it has to be installed on all the VMs in my PCF deployment? There isn't a way I can put ClamAV on just a subset of my VMs? or is there? 

2. How do customers know how many VMs they have in their PCF deployments or how many ClamAVs are installed? 

3. The screenshot is a bit confusing — the loadbalancer field is the one highlighted, and the intro text talks about loadbalancing... but I'm still guessing that the field I need to set is the "Automatic: 1" ? Is that correct?

**Comment by DennyHoang** [comment]
@jncd 

1. An operator could potentially configure ClamAV manually with runtime configs to be only deployed on a subset of environments. Or, when the clamav tile is added, and they decide to only apply changes to PKS and not PAS, for example, then only PKS vms will have ClamAV and PAS will not until they apply changes to that tile.

2. Hmm, for counting how many, they may have to manually count all the "instances" found in each tile's resource config or run a `bosh vms` command or manually checking in their iaas and see how many there are. I don't know if it is in scope for us to explain how to determine the number of VMs in their foundation. If you think otherwise, let me know.

3. Yes, we do not need to manually configure load balancing. What we are asking the user is to configure the Instances column. We do not need a load balancer to be configured by the user at any point for clamav-mirror because we use internal addresses (bosh-dns) which will do load balancing internally. 

4. Huh, which version of Ops Manager are you using? I tried installing clamav-mirror on v2.6 and it shows what is currently shown in the docs.

**Comment by jncd** [comment]
Thanks for all your answers. Very helpful.
I just noticed that the test build I was installing on is a 2.7 Ops
Manager.

**Comment by DennyHoang** [comment]
Sure, sounds good to me

**Pull request merged**
