### PR TITLE
Add Releases header

### PR DESCRIPTION
**Pull request by dlresende**
The Cryogenics team need this as a reference point so that our
automation can magically add release notes and submit PRs.

[#182198764]

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks!

**Comment by RichardJJG** [comment]
Should I cherry-pick these changes to any earlier branches, @dlresend?

**Comment by RichardJJG** [comment]
@dlresende, some older versions are still in development, according to the [README table](https://github.com/pivotal-cf/docs-addon-antivirus/blob/master/README.md). Should I cherry-pick these changes to those older branches?

**Comment by snneji** [comment]
@RichardJJG only 2.3 is in support

**Pull request merged**
