### PR TITLE
[#160122112] document how to configure scheduled scan times

### PR DESCRIPTION
**Pull request by drlau**
Signed-off-by: Carl He <jhe@pivotal.io>

### CODE REVIEW

**Comment by seviet** [comment]
thanks @drlau!

**Comment by xtreme-alvin-hsieh** [comment]
@seviet, great catch! Would you be able to make the switch for us, by simply re-ordering the two bullet points? If not, we can do it.

I also noticed that for certain sections where we give them a sample yml, there is a line break between "version: x.x.x" and "addons:", ie. line 273, 351, 378, 397, 433, 464. In the first two example, which are base linux and base windows sample, there is no line. We should remove the line.

Furthermore, do we need to cherrypick this back to the 1.4 branch? I will be making a pull request for the index file and release notes, and I'm not sure which branch I should use now.

Thanks.

**Comment by xtreme-alvin-hsieh** [comment]
@ghanna2017 @Pivotal-Christopher-Wong for context.

**Comment by seviet** [comment]
@xtreme-alvin-hsieh cool! yes, i can make that change. re: cherry-picking, if this feature is supported in 1.4, yes-- we'll need to cherry-pick this to the 1.4 branch (along with the other cleanup pieces.) one more question-- i noticed that the template has a `-` character under the `addons.name` property whereas some of the other yaml samples are missing the `-`. for example, see https://github.com/pivotal-cf/docs-addon-antivirus/blob/14db8b2660848353ea23decdc8afb03031ffd837/index.html.md.erb#L94 vs. https://github.com/pivotal-cf/docs-addon-antivirus/blob/14db8b2660848353ea23decdc8afb03031ffd837/index.html.md.erb#L395 -- which is correct? thanks!!!

**Pull request merged**
